name: Docker

#   schedule:
#    - cron: '30 8 * * 4'
#

on:
 workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: docker-nginx-headers-more
          registry: ghcr.io
          dockerfile: ./debian/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    
